class DE(object):
    MENU_FILE = "Datei"
    MENU_NEW = "Neu"
    MENU_OPEN = "Öffnen"
    MENU_SAVE = "Speichern"
    MENU_PREFS = "Einstellungen"
    MENU_EXIT = "Beenden"

    PREFS_FONTS = "Schriftart"
    PREFS_SIZE = "Schriftgröße"
    PREFS_BOLD = "fett"
    PREFS_ITALIC = "kursiv"
    PREFS_FG = "Textfarbe"
    PREFS_BG = "Hintergrund"
    PREFS_DOTS = "..."
    PREFS_TEST = "The quick brown fox jumped ofer the lazy dog."
    PREFS_OK = "Speichern"
    PREFS_CANCEL = "Abbrechen"

    SEARCH_TITLE = "Suche ..."